### ISSUE TITLE
veDTStamp in VEvent

### ISSUE THREAD

**Issue by xkollar** [chrra/iCalendar#24]
Specification <https://tools.ietf.org/html/rfc2445#section-4.6.1> says that dtstamp is optional... in event. So maybe `veDTStamp :: DTStamp` would be better `veDTStamp :: Maybe DTStamp`?

**Comment by xkollar** [comment]
... interesting RFC, really... [section on Date/Time Stamp](https://tools.ietf.org/html/rfc2445#section-4.8.7.2) says that `DTSTAMP` is mandatory for `VEVENT`... `:-(`.

**Comment by pweaver** [comment]
FYI, the latest ICalendar RFC is 5545, 2445 is an older one.
https://tools.ietf.org/html/rfc5545

**Comment by xkollar** [comment]
Thanks
