### ISSUE TITLE
iCalendar fails to link properly with stack (quick fix available already)

### ISSUE THREAD

**Issue by jarmohurri** [chrra/iCalendar#31]
Greetings.

In `stack`, including iCalendar currently via `extra-deps` results in linker error for undefined symbol `iCalendarzm0zi4zi0zi4zm8IJAR7jAxdO8cUMbVHntW4_PathszuiCalendar_version1_closure`.

Fortunately an easy fix is available by trofi in his master branch [in this commit](https://github.com/trofi/iCalendar/commit/9cd4776952ed145bc2a53e62028c2b4d199b254e). Could it please be merged into this main repo (and hopefully onwards to Hackage).

**Comment by chrra** [comment]
iCalendar 0.4.0.5 with this fix is uploaded to hackage.
